
spring:

  application:
    name: monefy app

  datasource:
    url: jdbc:postgresql://localhost:5432/monefy
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  thymeleaf:
    check-template-location: false

  security:
    jwt:
      secret: ${JWT_SECRET:averylong64bytesupersecretkeythatnooneknows1234567890abcd}
      expiration-ms: 86400000
    user:
      name: root
      password: root333